import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Grid from '../components/Grid'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>The Law</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero />

      <main className={styles.main} style={{ backgroundColor: "#f4f4f4" }}>
        <div className={styles.container}>

          {/* <About /> */}
          <Grid />

        </div>
      </main>
    </>
  )
}

export default Home
